<a href="https://colab.research.google.com/github/mandoo2/machineleaning_study/blob/main/dacon221111.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np

In [8]:
arrayy1 = np.array([1, 2, 3])
print(arrayy1)
print("arrayy1's array shape: ", arrayy1.shape)

arrayy2 = np.array([[1, 2, 3], [4, 5, 6]])
print(arrayy2)
print("arrayy2's array shape: ", arrayy2.shape)

arrayy3 = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9]]])
print(arrayy3)
print("arrayy3's array shape: ", arrayy3.shape)

[1 2 3]
arrayy1's array shape:  (3,)
[[1 2 3]
 [4 5 6]]
arrayy2's array shape:  (2, 3)
[[[1 2 3]
  [4 5 6]
  [7 8 9]]]
arrayy3's array shape:  (1, 3, 3)


In [9]:
list1 = [1.5, 2.4, 3.7]
print(type(list1))

array1 = np.array(list1)
print(type(array1))

print(array1, array1.dtype)

<class 'list'>
<class 'numpy.ndarray'>
[1.5 2.4 3.7] float64


In [10]:
list2 = [1, 2, 'test']
array2 = np.array(list2)
print(array2, array2.dtype)

['1' '2' 'test'] <U21


In [11]:
array_int = np.array([1, 2, 3])
print(array_int, array_int.dtype)

array_float = array_int.astype('float64')
print(array_float, array_float.dtype)

[1 2 3] int64
[1. 2. 3.] float64


In [14]:
sequence_array = np.arange(10)
print(sequence_array)

[0 1 2 3 4 5 6 7 8 9]


In [15]:
zeros1 = np.zeros((3,2))
print(zeros1)

[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [17]:
zeros2 = np.zeros([3, 2])
print(zeros2)

[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [18]:
ones1 = np.ones((3, 2))
print(ones1)

[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [19]:
ones2 = np.ones([3, 2])
print(ones2)

[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [20]:
rd = np.random.randn(3, 2)
print(rd)

[[ 1.45644852  1.59548631]
 [ 0.27074867  1.37514083]
 [-0.10424886 -0.48826534]]


In [21]:
array1 = np.arange(10)
print("array1:\n", array1)

array2 = array1.reshape(2, 5)
print("array2:\n", array2)

array1:
 [0 1 2 3 4 5 6 7 8 9]
array2:
 [[0 1 2 3 4]
 [5 6 7 8 9]]


In [22]:
array1 = np.arange(8)

array3d = array1.reshape((2, 2, 2))
print("array3d: \n", array3d)

array2d = array3d.reshape(-1, 1)
print("array2d:\n", array2d)

array3d: 
 [[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]
array2d:
 [[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]]


In [23]:
array1 = np.arange(start = 1, stop = 10)
print('array1:', array1)

print('array1[2]:', array1[2])

print('맨 뒤의 값:', array1[-1], '\n맨 뒤에서 두 번째 값:', array1[-2])

array1: [1 2 3 4 5 6 7 8 9]
array1[2]: 3
맨 뒤의 값: 9 
맨 뒤에서 두 번째 값: 8


In [24]:
array1[0] = 9
print(array1)

[9 2 3 4 5 6 7 8 9]


In [25]:
array2 = array1.reshape(3, 3)
print(array2)

print('1행 1열의 값', array2[0, 0])
print('1행 2열의 값', array2[0, 1])

[[9 2 3]
 [4 5 6]
 [7 8 9]]
1행 1열의 값 9
1행 2열의 값 2


In [27]:
array4 = np.random.randn(2, 2, 4, 5).round(3)
print(array4)
print("-"*45)
print('\n array4[0, 0]: \n', array4[0, 0])
print('\n array4[0, 1]: \n', array4[0, 1])
print('\n array4[1, 0]: \n', array4[1, 0])
print('\n array4[1, 1]: \n', array4[1, 1])
print("-"*45)
print('\n array4[0][1][3]:\n', array4[0][1][3])
print('\n array4[0][1][3][4]:\n', array4[0, 1, 3, 4])


[[[[ 0.986  0.28   0.406 -1.172 -1.004]
   [-0.209  0.602  0.697 -0.201  1.947]
   [ 0.401 -0.117  1.469  1.437  0.476]
   [-1.084 -0.39   0.601  0.404 -0.764]]

  [[ 0.056  0.248  0.642  1.266 -0.547]
   [ 2.644 -0.702  2.135 -2.325 -1.915]
   [ 0.437  0.258  0.872  0.594  1.119]
   [-1.346  0.731 -0.73   0.132  0.398]]]


 [[[ 1.118 -0.638  0.505 -1.864  0.166]
   [ 0.893  0.251  0.718  0.654 -1.315]
   [-1.322 -0.438 -0.163  1.395 -1.341]
   [ 0.537 -0.418  1.12  -0.41  -0.178]]

  [[-0.843 -0.261  0.092  1.417  0.346]
   [-0.18  -0.015 -0.763  1.293  0.351]
   [ 0.006 -0.181  0.548 -2.595 -1.236]
   [-0.37  -1.706  0.01  -0.77  -0.186]]]]
---------------------------------------------

 array4[0, 0]: 
 [[ 0.986  0.28   0.406 -1.172 -1.004]
 [-0.209  0.602  0.697 -0.201  1.947]
 [ 0.401 -0.117  1.469  1.437  0.476]
 [-1.084 -0.39   0.601  0.404 -0.764]]

 array4[0, 1]: 
 [[ 0.056  0.248  0.642  1.266 -0.547]
 [ 2.644 -0.702  2.135 -2.325 -1.915]
 [ 0.437  0.258  0.872  0.594  1.119]


In [29]:
array1 = np.arange(start = 1, stop = 10)
print(array1[0:2])

[1 2]


In [30]:
print(array1,'\n')
print(array1[:5])
print(array1[3:])
print(array1[:])

[1 2 3 4 5 6 7 8 9] 

[1 2 3 4 5]
[4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]


In [31]:
array1 = array1.reshape(3, 3)
print(array1)
print('-'*10)

print(array1[0:2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
----------
[[1 2 3]
 [4 5 6]]


In [32]:
print(array1)
print("-"*10)

print(array1[0:3, 1:3])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
----------
[[2 3]
 [5 6]
 [8 9]]


In [33]:
print(array1)
print('-'*10)

print(array1[1:, :2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
----------
[[4 5]
 [7 8]]


In [34]:
print(array1)
print('-'*10)

print(array1[:3, 0])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
----------
[1 4 7]


In [35]:
print(array1)
print('-'*10)

print(array1[[0,2]])
print('-'*10)

print(array1[[0,2], 1])
print('-'*10)

print(array1[[0,2], 0:2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
----------
[[1 2 3]
 [7 8 9]]
----------
[2 8]
----------
[[1 2]
 [7 8]]


In [36]:
boolean = array1[array1>3]

print('array1 > 3인 불린 인덱싱 결과 값:',  boolean)

print('객체반환: \n', array1>3)

array1 > 3인 불린 인덱싱 결과 값: [4 5 6 7 8 9]
객체반환: 
 [[False False False]
 [ True  True  True]
 [ True  True  True]]


In [37]:
org_array = np.array([4, 2, 8, 6])

print('원본 행렬: ', org_array)
print('np.sort 호출 후 반환된 행렬: ', np.sort(org_array))
print('np.sort 호출 후 원본 행렬: ', org_array)
print('ndarray.sort 호출 후 반환된 행렬:', org_array.sort())
print('ndarray.sort 호출 후 원본 행렬:', org_array)

원본 행렬:  [4 2 8 6]
np.sort 호출 후 반환된 행렬:  [2 4 6 8]
np.sort 호출 후 원본 행렬:  [4 2 8 6]
ndarray.sort 호출 후 반환된 행렬: None
ndarray.sort 호출 후 원본 행렬: [2 4 6 8]


In [38]:
print('내림차순 정렬: ', np.sort(org_array)[::-1])


내림차순 정렬:  [8 6 4 2]


In [41]:
array2 = np.array([[8, 1], [7,12]])
print(array2)

print(np.sort(array2, axis = 1))
print(np.sort(array2, axis = 0))

[[ 8  1]
 [ 7 12]]
[[ 1  8]
 [ 7 12]]
[[ 7  1]
 [ 8 12]]


In [42]:
org_array = np.array([4, 2, 8, 6])
print(np.argsort(org_array))

[1 0 3 2]


In [43]:
print(np.argsort(org_array)[::-1])

[2 3 0 1]


In [44]:
a = np.array([[1, 2, 3], [4, 5, 6]])
print(a)

b = np.array([[7, 8], [9, 10], [11, 12]])
print(b)

print(np.dot(a, b))

[[1 2 3]
 [4 5 6]]
[[ 7  8]
 [ 9 10]
 [11 12]]
[[ 58  64]
 [139 154]]


In [45]:
a= np.array([[1, 2], [3, 4]])
print(a)
print(np.transpose(a))

[[1 2]
 [3 4]]
[[1 3]
 [2 4]]


In [46]:
a = np.array([[11, 12, 13], [2, 3, 4]])
print(a)
print(a+a)

[[11 12 13]
 [ 2  3  4]]
[[22 24 26]
 [ 4  6  8]]


In [47]:
print(a)
print(a + 13)
print(a - 13)
print(a * 3)

[[11 12 13]
 [ 2  3  4]]
[[24 25 26]
 [15 16 17]]
[[ -2  -1   0]
 [-11 -10  -9]]
[[33 36 39]
 [ 6  9 12]]


In [49]:
a1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
a2 = np.array([[1, 2, 3,], [1, 2, 3], [1, 2, 3]])

print(a1, a2, a1+a2)

[[1 2 3]
 [4 5 6]
 [7 8 9]] [[1 2 3]
 [1 2 3]
 [1 2 3]] [[ 2  4  6]
 [ 5  7  9]
 [ 8 10 12]]


In [50]:
broad = np.arange(10).reshape(5, 2)
casting = np.arange(10, 12)

print(broad)
print("-"*10)
print(casting)
print('-'*10)
print(broad+casting)

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
----------
[10 11]
----------
[[10 12]
 [12 14]
 [14 16]
 [16 18]
 [18 20]]


In [51]:
print(a)
print(a.sum())

[[11 12 13]
 [ 2  3  4]]
45


In [52]:
print(a.sum(axis=1))
print(a.sum(axis=0))

[36  9]
[13 15 17]


In [53]:
print(a.mean())

7.5


In [54]:
print(a.prod())

41184


In [55]:
print(a.max())
print(a.min())

13
2


In [56]:
print(a)
print(a[1].max())
print(a[0].min())

[[11 12 13]
 [ 2  3  4]]
4
11


In [57]:
print(a.argmax())
print(a.argmin())

2
3


In [58]:
print(a.std())
print(a.var())

4.573474244670748
20.916666666666668
